### ISSUE TITLE
bug in `array_add`

### ISSUE THREAD

**Issue by chochkov** [adjust/pg-numhstore#18]
@roa 

see this https://github.com/adjust/pg-numhstore/compare/array_add_fix?expand=1 for an illustration of a bug that results in us having cohorts with 0 valued keys for apps that make no revenue.

Could you please fix that

**Comment by chochkov** [comment]
that thing fails to build

**Comment by roa** [comment]
what is the expected result of

```
SELECT array_add(ARRAY[1,2,3]::text[], ARRAY[1,NULL,3]);
```

?

**Comment by chochkov** [comment]
the expected result would be: 

```
  "1"=>"1", "3"=>"3"
```

**Comment by chochkov** [comment]
strangely, there's already a spec that seems to cover `NULL` args and that one passes, but the one I added doesnt

**Comment by roa** [comment]
is it possible, that a value can be "0"?

**Comment by chochkov** [comment]
From my perspective, `0` should be respected, but `NULL`s ignored. However, I'd like @rapimo's view on this

**Comment by roa** [comment]
that is super hard and expensive as we would have to evaluate the array as a c and postgres datatype array. what is the difference between "0" and "NULL"?

**Comment by roa** [comment]
it is fixed here, if "0" and "NULL" is the same:

https://github.com/adjust/pg-numhstore/pull/19

**Comment by chochkov** [comment]
I think @rapimo should have the final say here.

**Comment by rapimo** [comment]
mmmh yeah not sure for me `0` is a valid value for a numhstore where `NULL` is a non existent key
so if it doesn't take too much effort I'd love to keep `0`

**Comment by rapimo** [comment]
so @roa can you go ahead ? I added a test case in 8fe486f

**Comment by roa** [comment]
i just tried:

in  an postgres integer array "0" and "NULL" is the same. if you explicitly set it to "0" it is set to NULL in the low level array. so i see no possibility to make that happen as i can not differ between both. any ideas?

**Comment by roa** [comment]
oh wait, i found something! hold on.

**Comment by roa** [comment]
@rapimo fixed. can you test if it works on mac os as well?
