### ISSUE TITLE
check that make works on linux

### ISSUE THREAD

**Issue by rapimo** [adjust/pg-numhstore#3]
I tried my very best to make the makefile a nice as possible

```
make
make install
make installcheck
make clean
```

all work for me on mac os (besides the warnings)
it now installs to

```
pg_config --pkglibdir
```

thats why I also rename add, count and uniq to
hstore_add, array_count and array_uniq to avoid naming clash
I also rename welle_add, welle_count and roa_uniq c- function respectively.

Can you check that it works on linux ?

**Comment by roa** [comment]
array_uniq, array_count and make installcheck dont work.

**Comment by roa** [comment]
sorry, array_uniq and hstore_add. it is because it only builds the module_big thingy, not the module thingy. that is why i had the 3 extra makefiles
